layout_spectrum: 1
typography_spectrum: 0.1960257
color:
  saturation: 0.6922663
  lightness: 0.1186896
  brandStrength: 0
  rhythmicContrast: 0.3875014
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: William G. Gambill
